### ISSUE TITLE
Offline workflow

### ISSUE THREAD

**Issue by arcanis** [arcanis/pmm#4]
Some users will not want to download things dynamically. This should be addressed in the available tools.

**Proposed workflow:**

A command (let's say `pmm hydrate`) would install a tarball within the package manager cache:

```
pmm hydrate yarn-1.22.4.tgz
# Yarn 1.22.4 is in the cache, no dynamic install
yarn --version
```

How these archives will be retrieved doesn't matter: users have the responsibility for that. Some popular options will be:

- Store them directly within the repositories
- Download them from a private registry
- Cache them when building the docker images

To make the tarball creation easier, pmm would include a `pmm pack yarn@1.22.4` command that would generate the tgz file for the given package manager (in a format suitable for `pmm hydrate`).

**Comment by arcanis** [comment]
Of note, this would also enable private proxies & registries at no configuration cost: users would just have to fetch the tarballs themselves, using their preferred tools. Basic example:

```
wget https://user:password@binaries.my-company.com/yarn-1.22.4.tgz
```

**Comment by arcanis** [comment]
cc @mmarchini

**Comment by mmarchini** [comment]
yeah, I think that works. Would it also be possible to have a global config file for pmm where we could set pmm to never download the package manager (useful for Docker images) or to always download without asking (useful for adventurous users on development environments), along other settings?

**Comment by arcanis** [comment]
It could - one tricky thing with configuration variables is that .. well .. you need to load this configuration, and things get ever so slightly more complicated. Do you think keeping that as an environment variable would work? Something like:

```
PMM_FALLBACK_BEHAVIOR=<none|request|accept>
```

**Comment by mmarchini** [comment]
yeah, environment variables could work too. I think configuration files are more user-friendly (especially for users not super familiar with Unix systems or for Windows users), but env variables work especially if we have a really limited set of configuration options.

**Comment by arcanis** [comment]
Implemented `pmm pack` & `pmm hydrate` + tests, along with the `PMM_ENABLE_NETWORK` environment value.
